### ISSUE TITLE
Cannot figure out the dev setup for this module?

### ISSUE THREAD

**Issue by papandreou** [nearform/node-cephes#3]
After upgrading my app to cephes (via `ttest@2.0.0` -> `distributions@2.0.0`) I noticed that I gained a lot of weight:

```
$ npm ls
<snip>
└─┬ ttest@2.0.0
  ├─┬ distributions@2.0.0
  │ └─┬ cephes@1.1.2
  │   └─┬ brfs@2.0.2
  │     ├─┬ quote-stream@1.0.2
  │     │ ├── buffer-equal@0.0.1
  │     │ ├── minimist@1.2.0 deduped
  │     │ └── through2@2.0.5 deduped
  │     ├── resolve@1.8.1 deduped
  │     ├─┬ static-module@3.0.2
  │     │ ├─┬ acorn-node@1.6.2
  │     │ │ ├── UNMET PEER DEPENDENCY acorn@6.1.1
  │     │ │ ├── acorn-dynamic-import@4.0.0
  │     │ │ ├── acorn-walk@6.1.1
  │     │ │ └── xtend@4.0.1 deduped
  │     │ ├─┬ concat-stream@1.6.2
  │     │ │ ├── buffer-from@1.1.1
  │     │ │ ├── inherits@2.0.3 deduped
  │     │ │ ├── readable-stream@2.3.6 deduped
  │     │ │ └── typedarray@0.0.6
  │     │ ├─┬ convert-source-map@1.6.0
  │     │ │ └── safe-buffer@5.1.2
  │     │ ├─┬ duplexer2@0.1.4
  │     │ │ └── readable-stream@2.3.6 deduped
  │     │ ├─┬ escodegen@1.9.1
  │     │ │ ├── esprima@3.1.3
  │     │ │ ├── estraverse@4.2.0 deduped
  │     │ │ ├── esutils@2.0.2 deduped
  │     │ │ ├── optionator@0.8.2 deduped
  │     │ │ └── source-map@0.6.1
  │     │ ├── has@1.0.3 deduped
  │     │ ├─┬ magic-string@0.22.5
  │     │ │ └── vlq@0.2.3
  │     │ ├─┬ merge-source-map@1.0.4
  │     │ │ └── source-map@0.5.7
  │     │ ├── object-inspect@1.4.1
  │     │ ├─┬ readable-stream@2.3.6
  │     │ │ ├── core-util-is@1.0.2 deduped
  │     │ │ ├── inherits@2.0.3 deduped
  │     │ │ ├── isarray@1.0.0 deduped
  │     │ │ ├── process-nextick-args@2.0.0
  │     │ │ ├── safe-buffer@5.1.2 deduped
  │     │ │ ├─┬ string_decoder@1.1.1
  │     │ │ │ └── safe-buffer@5.1.2 deduped
  │     │ │ └── util-deprecate@1.0.2 deduped
  │     │ ├─┬ scope-analyzer@2.0.5
  │     │ │ ├── array-from@2.1.1
  │     │ │ ├─┬ es6-map@0.1.5
  │     │ │ │ ├─┬ d@1.0.0
  │     │ │ │ │ └── es5-ext@0.10.49 deduped
  │     │ │ │ ├─┬ es5-ext@0.10.49
  │     │ │ │ │ ├── es6-iterator@2.0.3 deduped
  │     │ │ │ │ ├── es6-symbol@3.1.1 deduped
  │     │ │ │ │ └── next-tick@1.0.0
  │     │ │ │ ├─┬ es6-iterator@2.0.3
  │     │ │ │ │ ├── d@1.0.0 deduped
  │     │ │ │ │ ├── es5-ext@0.10.49 deduped
  │     │ │ │ │ └── es6-symbol@3.1.1 deduped
  │     │ │ │ ├── es6-set@0.1.5 deduped
  │     │ │ │ ├── es6-symbol@3.1.1 deduped
  │     │ │ │ └─┬ event-emitter@0.3.5
  │     │ │ │   ├── d@1.0.0 deduped
  │     │ │ │   └── es5-ext@0.10.49 deduped
  │     │ │ ├─┬ es6-set@0.1.5
  │     │ │ │ ├── d@1.0.0 deduped
  │     │ │ │ ├── es5-ext@0.10.49 deduped
  │     │ │ │ ├── es6-iterator@2.0.3 deduped
  │     │ │ │ ├── es6-symbol@3.1.1 deduped
  │     │ │ │ └── event-emitter@0.3.5 deduped
  │     │ │ ├─┬ es6-symbol@3.1.1
  │     │ │ │ ├── d@1.0.0 deduped
  │     │ │ │ └── es5-ext@0.10.49 deduped
  │     │ │ ├── estree-is-function@1.0.0
  │     │ │ └── get-assigned-identifiers@1.2.0
  │     │ ├── shallow-copy@0.0.1
  │     │ ├─┬ static-eval@2.0.2
  │     │ │ └── escodegen@1.9.1 deduped
  │     │ └── through2@2.0.5 deduped
  │     └─┬ through2@2.0.5
  │       ├── readable-stream@2.3.6 deduped
  │       └── xtend@4.0.1
<snip>
```

Since it seems like `brfs` is pulling all that in here, and it looks like some kind of build step, I wanted to check if that could somehow be demoted to a dev dep.

However, when I clone this repo and run `npm i` and `npm test` all test fail because I don't have `index.js`:

```
$ npm test

> cephes@1.1.2 test /Users/andreaslind/work/node-cephes
> tap test/*.test.js


/Users/andreaslind/work/node-cephes/test/actual.test.js:5
const cephes = require('../index.js');
               ^
/Users/andreaslind/work/node-cephes/test/actual.test.js:1
Error: Cannot find module '../index.js'
Require stack:
- /Users/andreaslind/work/node-cephes/test/actual.test.js
    at Object.<anonymous> (/Users/andreaslind/work/node-cephes/test/actual.test.js:5:16)
    at Generator.next (<anonymous>)
/Users/andreaslind/work/node-cephes/cephes-wrapper.js:1
Error: ENOENT: no such file or directory, open '/Users/andreaslind/work/node-cephes/cephes.wasm'
    at Object.openSync (fs.js:448:3)
    at Proxy.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/Users/andreaslind/work/node-cephes/cephes-wrapper.js:8:22)
    at Generator.next (<anonymous>)
test/actual.test.js ................................... 0/1
  not ok test/actual.test.js
    timeout: 30000
    file: test/actual.test.js
    childId: 0
    command: /Users/andreaslind/.nvm/versions/node/v11.12.0/bin/node
    args:
      - '-r'
      - /Users/andreaslind/work/node-cephes/node_modules/esm/esm.js
      - test/actual.test.js
    stdio:
      - 0
      - pipe
      - 2
    cwd: /Users/andreaslind/work/node-cephes
    exitCode: 1
```

I see that `index.js` is being `.gitignore`d, but I don't see any build steps in `package.json` -- is there something missing from the repo?

**Comment by papandreou** [comment]
Ping @AndreasMadsen? I would really like to be able to move over to this module to avoid dealing with https://github.com/AndreasMadsen/mathfn/commit/219a7a346bbbef2475f901ca93bfc7e90d0cc86c#commitcomment-33072535

**Comment by AndreasMadsen** [comment]
@papandreou Looks like it all comes from `brfs`. This is only required for the browserify build. Could you see if there is a way to only depend on that in a browserify context?

**Comment by AndreasMadsen** [comment]
Regarding the `index.js` file and how to build, look in https://github.com/nearform/node-cephes/blob/master/CONTRIBUTING.md

**Comment by papandreou** [comment]
Ah, thanks for that link, unfortunately I cannot get the instructions to work on my mac or my Ubuntu box. In both cases it fails at the `clang-rename` step:

```
clang-rename \
		-qualified-name=ceil -new-name=ignore_ceil \
		-qualified-name=floor -new-name=ignore_floor \
		-i cephes/floor.c
make: clang-rename: No such file or directory
make: *** [download] Error 1
```

I've failed to find a package that provides that binary.

> Looks like it all comes from `brfs`. This is only required for the browserify build. Could you see if there is a way to only depend on that in a browserify context?

Looks like you can think of it as a pretty simple transformation that just inlines those files into the bundle, so it could easily happen at package publication time? From looking at other projects that use `brfs` it seems like the standard solution would be to have a `prepublishOnly` hook that browserifies `cephes-browser.js`, points the `browser` field in package.json at it (and includes it in the package). Then all your dependents don't need to install all the modules required for creating the bundle.

I don't feel like attempting that change without having a working dev setup, though.

**Comment by AndreasMadsen** [comment]
@papandreou `clang-rename` should be a part of `emscripten`, you just need to enable the environment.

> From looking at other projects that use brfs it seems like the standard solution would be to have a `prepublishOnly` hook that browserifies cephes-browser.js ...

I would properly just make it a part of the build step then. I suspect that `prepublish` hooks are not fun to debug.

**Comment by papandreou** [comment]
> `clang-rename` should be a part of `emscripten`, you just need to enable the environment.

Ah, I finally made it work, had to edit `~/.emscripten` to make sure that it uses the bundled llvm instead of the other one I had installed. But that's not the fault of this project :)

Ran into some trouble with `browserify`, but I think I managed to make a build with `rollup` now: #4

**Comment by AndreasMadsen** [comment]
@papandreou Great that you got it working. Let us know if something was unclear, or even better make a contribution to https://github.com/nearform/node-cephes/blob/master/CONTRIBUTING.md that elaborates on the parts that confused you.

**Comment by papandreou** [comment]
I think all the stuff I had to tweak might be due to homebrew's packaging of emscripten, so I'm not sure it belongs in `CONTRIBUTING.md` here. For the record I ended up changing these in `~/.emscripten`:

```
EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN', '/usr/local/Cellar/emscripten/1.38.32/libexec')) # directory

LLVM_ROOT = os.path.expanduser(os.getenv('LLVM', '/usr/local/Cellar/emscripten/1.38.32/libexec/llvm/bin')) # directory
```

Also, I had to tweak some other things get the thing to compile and run:

```diff
diff --git a/Makefile b/Makefile
index eec3dd2..d400d85 100644
--- a/Makefile
+++ b/Makefile
@@ -67,7 +67,7 @@ download: | cephes/
        @# Rename (effectively remove) ceil, floor as they have native
        @# WebAssembly equivalents (f64.ceil, and f64.floor).
        @# It will continue to contain defintions for frexp, and ldexp
-       clang-rename \
+       /usr/local/opt/llvm\@8/bin/clang-rename \
                -qualified-name=ceil -new-name=ignore_ceil \
                -qualified-name=floor -new-name=ignore_floor \
                -i $(CEPHESDIR)/floor.c
@@ -150,7 +150,7 @@ cephes.wasm: $(JS_OBJS)
                )]" \
                -s EXTRA_EXPORTED_RUNTIME_METHODS="['writeArrayToMemory', 'stackAlloc', 'stackSave', 'stackRestore', 'getValue']" \
                -s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="[]" \
-               -s TOTAL_MEMORY=1MB \
+               -s TOTAL_MEMORY=2MB \
                -s TOTAL_STACK=1MB \
                -s NO_FILESYSTEM=1 \
                -s ENVIRONMENT='node' \
diff --git a/cephes-wrapper.js b/cephes-wrapper.js
index e3b295f..81a0486 100644
--- a/cephes-wrapper.js
+++ b/cephes-wrapper.js
@@ -2,7 +2,7 @@
 const fs = require('fs');
 
 const TOTAL_STACK = 1024 * 1024; // 1MB
-const TOTAL_MEMORY = 1024 * 1024; // 1MB
+const TOTAL_MEMORY = 2 * 1024 * 1024; // 2MB
 const WASM_PAGE_SIZE = 64 * 1024; // Defined in WebAssembly specs
 
 // This must be brfs friendly -- see https://github.com/browserify/brfs
```

Again, it could all be due to homebrew weirdness or a weird setup on my machine, so I'm not sure it applies generally.

**Comment by AndreasMadsen** [comment]
There could be some validity to the `TOTAL_MEMORY` change, but the rest is definitely related to your setup.
